version: '3.1'

services:
  php:
    build: docker/images/php
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ./app/:/var/www/html/
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/data/apache/log/:/var/log/apache2/
      - ./docker/data/msmtp/log.log:/var/log/msmtp.log

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql/
    ports:
      - "3306:3306"

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"