public enum		Events
{
	ReceivedArguments,
	ReceivedExpression,
	ParsedTokens,
	ProcessedUnaryMinus,
	ProcessedImplicitMultiplication,
	BuiltElements,
	GroupedPower,
	GroupedMultiplicationAndDivision,
	GroupedAdditionAndSubtraction,
	ReducedPower,
	ReducedMultiplicationAndDivision,
	ReducedEquality,
	ReducedAdditionAndSubtraction,
	ExtractedTerms,
	SortedTerms,
	SolvedEquation
}