package view.open;

public enum			ButtonId
{
	// Hero Selector
	HERO_SELECTOR_CREATE_0,
	HERO_SELECTOR_CREATE_1,
	HERO_SELECTOR_CREATE_2,
	HERO_SELECTOR_CREATE_3,
	HERO_SELECTOR_SELECT_0,
	HERO_SELECTOR_SELECT_1,
	HERO_SELECTOR_SELECT_2,
	HERO_SELECTOR_SELECT_3,
	HERO_SELECTOR_DELETE_0,
	HERO_SELECTOR_DELETE_1,
	HERO_SELECTOR_DELETE_2,
	HERO_SELECTOR_DELETE_3,

	// Name entry
	NAME_ENTRY_ENTER,

	// Class selector
	CLASS_SELECTOR_SELECT_0,
	CLASS_SELECTOR_SELECT_1,
	CLASS_SELECTOR_SELECT_2,
	CLASS_SELECTOR_SELECT_3;

	public ButtonId	applyOffset(int offset)
	{
		return values()[this.ordinal() + offset];
	}
}
